modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT"

[[mods]]
modId="commandsspy"
version="${version}"
displayName="Commands Spy"
authors="Ultra_MC"
description='''Log commands to server console.'''

[[dependencies.commandsspy]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.commandsspy]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
