name: 'Java Gradle Setup'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7.0.1
    - uses: gradle/actions/wrapper-validation@v6.3.0
    - uses: actions/setup-java@v5.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v6.3.0
      with:
        cache-read-only: false
    - run: chmod +x ./gradlew
      shell: bash
