name: 'Java Gradle Setup'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v3
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - run: chmod +x ./gradlew
      shell: bash
